function convertToBBCode() {
  // Get the HTML input
  var html = document.getElementById("html-input").value;
  // Convert the HTML to BBCode
  var bbcode = html

      .replace(/<p class="([^"]+)">(.*?)<\/p>/gs, function (match, className, content){return `[container:${className}][p]${content}[/p][/container]`;})
      .replace(/<p>(.*?)<\/p>/gs, function (match, content){return `[p]${content}[/p]`;})
      .replace(/<b>(.*?)<\/b>/gs, function (match, content){return `[b]${content}[/b]`;})
      .replace(/<em>(.*?)<\/em>/gs, function (match, content){return `[i]${content}[/i]`;})
      .replace(/<dropcap>(.*?)<\/dropcap>/gs, function (match, content){return `[dc]${content}[/dc]`;})
      .replace(/<h1>(.*?)<\/h1>/gs, function (match, content){return `[h1]${content}[/h1]`;})
      .replace(/<h2>(.*?)<\/h2>/gs, function (match, content){return `[h2]${content}[/h2]`;})
      .replace(/<h3>(.*?)<\/h3>/gs, function (match, content){return `[h3]${content}[/h3]`;})
      .replace(/<h4>(.*?)<\/h4>/gs, function (match, content){return `[h4]${content}[/h4]`;})
      .replace(/<h5>(.*?)<\/h5>/gs, function (match, content){return `[h5]${content}[/h5]`;})
      .replace(/<u>(.*?)<\/u>/gs, function (match, content){return `[u]${content}[/u]`;})
      .replace(/<i>(.*?)<\/i>/gs, function (match, content){return `[i]${content}[/i]`;})
      .replace(/<s>(.*?)<\/s>/gs, function (match, content){return `[s]${content}[/s]`;})
      .replace(/<small>(.*?)<\/small>/gs, function (match, content){return `[small]${content}[/small]`;})
      .replace(/<sup>(.*?)<\/sup>/gs, function (match, content){return `[sup]${content}[/sup]`;})
      .replace(/<sub>(.*?)<\/sub>/gs, function (match, content){return `[sub]${content}[/sub]`;})
      .replace(/<pre>(.*?)<\/pre>/gs, function (match, content){return `[pre]${content}[/pre]`;})
      .replace(/<blockquote>(.*?)<\/blockquote>/gs, function (match, content){return `[quote]${content}[/quote]`;})
      .replace(/<details>(.*?)<\/details>/gs, function (match, content){return `[spoiler]${content}[/spoiler]`;})
      .replace(/<abbr title='([^']+)'>/g, "[tooltip:$1]")
      .replace(/<\/abbr>/g, "[/tooltip]")
      .replace(/<br>/g, "[br]")
      .replace(/<br \/>/g, "[br]")
      .replace(/<hr>/g, "[hr]")
      .replace(/<p style="text-align: left;">(.*?)<\/p>/gs, function (match, content){return `[left]${content}[/left]`;})
      .replace(/<p style="text-align: center;">(.*?)<\/p>/gs, function (match, content){return `[center]${content}[/center]`;})
      .replace(/<p style="text-align: right;">(.*?)<\/p>/gs, function (match, content){return `[right]${content}[/right]`;})
      .replace(/<p style="text-align: justify;">(.*?)<\/p>/gs, function (match, content){return `[justify]${content}[/justify]`;})
      .replace(/<ul class="([^"]+)">(.*?)<\/ul>/gs, function (match, className, content){return `[container:${className}][ul]${content}[/ul][/container]`;})
      .replace(/<ul>/g, "[ul]")
      .replace(/<\/ul>/g, "[/ul]")
      .replace(/<ol class="([^"]+)">(.*?)<\/ol>/gs, function (match, className, content){return `[container:${className}][ol]${content}[/ol][/container]`;})
      .replace(/<ol>/g, "[ol]")
      .replace(/<\/ol>/g, "[/ol]")
      .replace(/<li class="([^"]+)">(.*?)<\/li>/gs, function (match, className, content){return `[section:${className}][li]${content}[/li][/section]`;})
      .replace(/<li>/g, "[li]")
      .replace(/<\/li>/g, "[/li]")
      .replace(/<h3 id='([^']+)'>/g, "[h3|$1]")
      .replace(/<span id='([^']+)'>/g, "[anchor|$1]")
      .replace(/<table>(.*?)<\/table>/gs, function (match, content){return `[table]${content}[/table]`;})
      .replace(/<tr>(.*?)<\/tr>/gs, function (match, content){return `[tr]${content}[/tr]`;})
      .replace(/<th style='width:(\d+)%'>/g, "[th:$1]")
      .replace(/<\/th>/g, "[/th]")
      .replace(/<td style='width:(\d+)%'>/g, "[td:$1]")
      .replace(/<td>(.*?)<\/td>/gs, function (match, content){return `[td]${content}[/td]`;})
      .replace(/<div class="col">(.*?)<\/div>/gs, function (match, content){return `[col]${content}[/col]`;})
      .replace(/<div class="row">(.*?)<\/div>/gs, function (match, content){return `[row]${content}[/row]`;})
      .replace(/<div class="/g, "[container:")
      .replace(/<div>/g, "[container:CLASS_HERE]")
      .replace(/<\/div>/g, "[/container]")
      .replace(/<span class="/g, "[section:")
      .replace(/<\/span>/g, "[/section]")
      .replace(new RegExp('<i class="(.*?)"></i>', "g"), "[section:$1] [/section]")
      .replace(/<img src="([^"]*)" style="width: ([\d\.]+)(em|rem|px); height: ([\d\.]+)(em|rem|px)">/g, function (match, src, width, widthUnit, height, heightUnit){
          if (widthUnit !== "px"){
              width = width * 16;
          }return `[img:${src}|center|${width}]`;})
      .replace(/;">/g, "]")
      .replace(/class="/g, ":")
      .replace(/" \/>/g, "]")
      .replace(/"\/>/g, "]")
      .replace(/src="/g, ":")
      .replace(/="/g, ":")
      .replace(/">/g, "]")
      .replace(/>/g, "]")
      .replace(/</g, "[")
      .replace(/<span style="color:(\w+)">(.*?)<\/span>/gs, function (match, color, content){return `[color:${color}]${content}[/color]`;})
      .replace(/<a href="(.*?)">(.*?)<\/a>/gs, function (match, url, content){return `[url:${url}]${content}[/url]`;});

  // Set the BBCode output
  document.getElementById("bbcode-output").value = bbcode;
}
